-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."employeers" add column "social_media_links_id" integer
--  null;
